#Training args
model_name_or_path: stabilityai/stablelm-base-alpha-7b
lora_weights_name_or_path: /ikerlariak/igarcia945/CoLLIE/pretrained_models/ace_ner/stablelm-base-alpha-7b
torch_dtype: "auto"
use_lora: true
int8_quantization: true


# dataset arguments
dataset_dir:
  /gscratch4/users/osainz006/CoLLIE/data/processed
test_tasks:
  - ace05.ner
max_seq_length: 2048
generation_max_length: 2048
ignore_pad_token_for_loss: true
ignore_prompt_loss: true

# checkpoint settings
output_dir: /ikerlariak/igarcia945/CoLLIE/pretrained_models/ace_ner/stablelm-base-alpha-7b
overwrite_output_dir: true
load_best_model_at_end: false
save_strategy: "epoch"
save_steps: 1000
save_total_limit: 999

# evaluation
do_train: false
do_eval: false
do_predict: true
evaluation_strategy: "steps"
eval_steps: 100
eval_delay: 0
predict_with_generate: true
evaluate_all_checkpoints: true

# batch size: 16 batch size * 8 gradaccum * 1 GPUs = 128
per_device_train_batch_size: 32
per_device_eval_batch_size: 2
gradient_accumulation_steps: 1
generation_num_beams: 4

# optimizer settings
optim: adamw_torch_fused
learning_rate: 0.0003
weight_decay: 0
num_train_epochs: 10
lr_scheduler_type: cosine
warmup_ratio: 0.03

# lora settings
lora_r: 16
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
  - query_key_value

# reporting
logging_strategy: steps
logging_first_step: true
logging_steps: 25
report_to: wandb
#report_to: none
run_name: "stablelm-base-alpha-7b-ace_ner"
disable_tqdm: false

# hub settings
push_to_hub: false
resume_from_checkpoint: false

# performance
bf16: false
fp16: true
torch_compile: false
ddp_find_unused_parameters: false